{{- if .Values.ingress.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{- if ne $key "snippets" }}
    {{ $key }}: {{ $value }}  
    {{- end }}
    {{- end }}
    nginx.org/server-snippets: >-
      {{ .Values.ingress.annotations.snippets.extra_parameters_snippets }}
{{ include "php.location_snippet" . | toString | indent 6 }} 
  name: {{ template "fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
{{- end }}
