kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}  
  {{- end }}
{{- end }}
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              serviceName: php-sample
              servicePort: 9000
