kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}  
    {{- end }}
    nginx.org/server-snippets: >-
      location {{ .Values.ingress.path }} {
      index  index.php;
      fastcgi_pass    {{ template "fullname" . }}-svc.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.port }};
      fastcgi_index   index.php;
      fastcgi_split_path_info ^(.+\.php)(/.+)$;
      include fastcgi_params;
      fastcgi_param   PATH_INFO $fastcgi_path_info;
      fastcgi_param   SCRIPT_FILENAME  /usr/src/app/public/index.php;
      fastcgi_param   SCRIPT_NAME index.php;
      {{- if .Values.ingress.location }}
      {{- range $key, $value := .Values.ingress.location }}
      {{ $key }}   {{ $value }};
      {{- end }}
      {{- end }}
      }   
  name: {{ template "fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host }}
