kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}  
    {{- end }}
    nginx.org/server-snippets: >-
      {{ .Values.annotations.extra_parameters_snippets }}
{{ include "php.location_snippet" . | toString | indent 6 }} 
  name: {{ template "fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host }}
