apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-exporter-config
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  config.yaml:
    listen:
      port: {{ .Values.metrics.port }}
      metrics_endpoint: "/metrics"

    namespaces:
      - name: 
        format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
        source:
          syslog:
            - listen_address: "udp://127.0.0.1:5531"
              format: "rfc3164"
        labels:
          app: {{ template "fullname" . }}
        histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
