# Default values for php
# # This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Pod priority
priority:
  enabled: false
  name: high-priority

# Note: replicaCount will not be used
# if autoscaling enabled
replicaCount: 1
healthchecks:
  enabled: true
  # type: <port|command>
  type: port
  # healthcheck command. Ignored if type is set to 'port'
  command:
    - somecommand
    - arg1
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 10
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 10
# volumes to mount in the pods
volumes:
  - name: "secret1"
    # secretName is the name of the secret to mount
    secretName: "mysecret-name"
    # mountPath is the directory where the secret will be mounted
    mountPath: "/path/to/mount"
env:
  RUN_COMMAND: php-fpm
image:
  php:
    repository: ""
    tag: 0.1.0
  pullPolicy: IfNotPresent
port: 9000
service:
  name: php-fpm
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    snippets:
      extra_parameters_snippets: tcp_nopush on; tcp_nodelay on;
      cache_enabled: true
      cache_config:
        expires: 2d
        fastcgi_cache: static-cache
        fastcgi_ignore_headers: Cache-Control
        fastcgi_cache_valid:
          - status_code: ""
            value: 60min
        fastcgi_cache_revalidate: "on"
        fastcgi_cache_use_stale: error timeout invalid_header updating http_500
        fastcgi_cache_background_update: "on"
      #extra_parameters_location: somestring value;
  host: example.com
  path: /
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 5
  maxReplicas: 20
  # Scaling based on memory
  memory:
    enabled: true
    averageUtilization: 70
  # Scaling based on cpu
  cpu:
    enabled: true
    averageUtilization: 70
metrics:
  enable: true
  port: 9113
  format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'
