# Default values for php
# # This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  php:
    repository: ""
    tag: 0.1.0
  nginx:
    repository: "bitnami/nginx"
    tag: 1.19.1
  pullPolicy: IfNotPresent
port: 9000
service:
  name: php-fpm
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  host: fenicio.com/
  path: /path
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
