# Default values for php
# # This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ""
  tag: 0.1.0
  pullPolicy: IfNotPresent
port: 9000
service:
  name: php-fpm
ingress:
  name: php-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /path
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
