{{- $global := .Values.global }}
{{- $ingress := .Values.ingress | default $global.ingress }}
{{- if $ingress.enabled }}
{{- $appName := .Values.appName | default $global.appName }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    {{- range $key, $value := $ingress.annotations }}
    {{- if ne $key "snippets" }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    {{- $whitelist := $ingress.whitelist_ip | default $global.whitelist_ip }}
    {{- if $whitelist.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join ", " $whitelist.ip_list }}
    {{- end }}
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
spec:
  tls:
    {{- range $host := $ingress.hosts }}
    - hosts:
       - {{ $host.name }}
      {{- if $host.secretName  }}
      secretName: {{ $host.secretName }}
      {{- end }}
    {{- end }}
  rules:
  {{- $service := .Values.service | default $global.service }}
  {{- range $host := $ingress.hosts }}
  - host: {{ $host.name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $appName }}
            port:
              number: {{ $service.port }}
  {{- end }}
{{- end }}