{{- $global := .Values.global }}
{{- $performanceTests := .Values.performanceTests | default $global.performanceTests }}
{{- if $performanceTests.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  {{- $appName := .Values.appName | default $global.appName }}
  name: {{ $appName }}-performance-test
spec:
  args:
  - name: configmap-name

  metrics:
  - name: k6
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              volumes:
              - name: test
                configMap:
                  name: {{ $appName }}-performance-test
                  defaultMode: 420
              containers:
              - name: k6
                image: loadimpact/k6
                args: ["run",  "/tmp/performanceTest/script.js"]
                volumeMounts:
                    - name: test
                      readOnly: true
                      mountPath: /tmp/performanceTest
              restartPolicy: Never
{{- end }}
