{{- $global := .Values.global }}
{{- $appName := .Values.appName | default $global.appName }}
{{- $phpFpmConfig := .Values.phpFpmConfig | default $global.phpFpmConfig }}
{{- if $phpFpmConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: www-php-fpm-{{ $appName }}
data: 
  www-php-fpm.conf: |-
{{ include "php-fpm-conf" $global | indent 4 }}
{{- end }}