{{- $global := .Values.global }}
{{- $ingress := .Values.ingress | default $global.ingress }}
{{- if $ingress.enabled }}
{{- $appName := .Values.appName | default $global.appName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName | default $global.appName  }}
  namespace: {{ .Release.Namespace }}
data:
  SCRIPT_FILENAME: "/usr/src/app/index.php"
{{- end }}
