{{- $global := .Values.global }}
{{- $ingress := .Values.ingress | default $global.ingress }}
{{- if $ingress.enabled }}
{{- $appName := .Values.appName | default $global.appName }}
{{- $performanceTests := .Values.performanceTests | default $global.performanceTests }}

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    {{- range $key, $value := $ingress.annotations }}
    {{- if ne $key "snippets" }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: {{ $appName }}
    {{- if not ( eq  $ingress.type "internal" )}}
      {{- $whitelist := $ingress.whitelist_ip | default $global.whitelist_ip }}
      {{- if $whitelist.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join ", " $whitelist.ip_list }}
      {{- end }}
    {{- end }}
    {{- $phpFpmExporter := .Values.phpFpmExporter| default $global.phpFpmExporter }}
    {{- if $phpFpmExporter.enabled }}
    nginx.ingress.kubernetes.io/server-snippet: |
      location {{ $phpFpmExporter.statusPath }} {
          return 403 {{ $phpFpmExporter.statusPath }};
      }
    {{- end }}
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ $ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $appName }}{{ if $performanceTests.enabled }}-active {{ end }}
            {{- $service := .Values.service | default $global.service }}
            port:
              number: {{ $service.port }}

  {{- if $performanceTests.enabled }}
  - host: {{ $ingress.host_preview | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $appName }}-preview
            {{- $service := .Values.service | default $global.service }}
            port:
              number: {{ $service.port }}
  {{- end }}
{{- end }}
