{{- $global := .Values.global }}
{{- $performanceTests := .Values.performanceTests | default $global.performanceTests }}
{{- if $performanceTests.enabled }}
{{- $appName := .Values.appName | default $global.appName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appName }}-performance-test
  namespace: {{ .Release.Namespace }}
data:
  {{- $config := .Values.performance_config | default $global.performance_config }}
  {{- $payload := .Values.performance_payload | default $global.performance_payload }}
  {{- $requests := .Values.performance_requests | default $global.performance_requests }}
  {{- $response_body := .Values.performance_response_body | default $global.performance_response_body }}
  {{- $script := .Values.performance_script | default $global.performance_script }}

  config.json: |
    {{- $config | nindent 4}}

  payload.json: |
    {{- $payload | nindent 4 }}

  requests.json: |
    {{- $requests | nindent 4 }}

  response-body.json: |
    {{- $response_body | nindent 4 }}

  script.js: |
    {{- $script | nindent 4}}
{{- end}}
