{{- $global := .Values.global }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  {{- $autoscaling := .Values.autoscaling | default $global.autoscaling }}
  {{- if not $autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: {{ .Values.appName }}
  template:
    metadata:
      labels:
        {{- if (.Values.labels.environment | default $global.environment) }}
        environment: {{ .Values.labels.environment | default $global.environment }}
        {{- end }}
        name: {{ .Values.appName }}
    spec:
      {{- $priority := .Values.priority | default $global.priority }}
      {{- if $priority.enabled }}
      priorityClassName: {{ $priority.name }}
      {{- end }}
      containers:
        - name: {{ .Values.appName }}
        {{- $env := .Values.env | default $global.env }}
        {{- $envSecrets := .Values.envSecrets | default $global.envSecrets }}
        {{- if or $env $envSecrets }}
          env:
          {{- range $key, $value := $env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $secret := $envSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ (split "/" $secret)._0 }}
                  key: {{ (split "/" $secret)._1 }}
          {{- end }}
        {{- end }}
          {{- $image := .Values.image | default $global.image }}
          {{- with $image }}
          image: '{{ $image.repository }}:{{ $image.tag }}'
          imagePullPolicy: {{  default "" $image.pullPolicy | quote }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.port | default $global.service.port }}

          {{- $resources := .Values.resources | default $global.resources }}
          resources:
            {{- toYaml $resources | nindent 12 }}

        {{- $healthchecks := .Values.healthchecks | default $global.healthchecks }}
        {{- with $healthchecks }}
          {{- if .enabled  }}
          readinessProbe:
          {{- if eq .type "port" }}
            tcpSocket:
              port: {{ $global.service.port }}
          {{- else if eq .type "command" }}
            exec:
              command:
                {{- range .command }} 
              - {{ . }}
                {{- end }}
          {{- end }}
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
            successThreshold: {{ .readinessProbe.successThreshold }}
            failureThreshold: {{ .readinessProbe.failureThreshold }}
          livenessProbe:
          {{- if eq .type "port"}}
            tcpSocket:
              port: {{ $global.service.port }}
          {{- else if eq .type "command" }}
            exec:
              command:
                {{- range .command }} 
              - {{ . }}
                {{- end }}
          {{- end }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
            successThreshold: {{ .livenessProbe.successThreshold }}
            failureThreshold: {{ .livenessProbe.failureThreshold }}
          {{- end }}
        {{- end }}
        {{- $volumes := .Values.volumes | default $global.volumes }}
        {{- if $volumes }}
          volumeMounts:
        {{- range $volumes }}
          {{- if .name }}
          - name: {{ .name }}
            mountPath: {{ .mountPath | quote }}
            {{- if .secretName }}
            readOnly: true
            {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
    {{- if $volumes }}
      volumes:
      {{- range $volumes }}
        {{- if .name }}
        - name: {{ .name }}
          {{- if .secretName }}
          secret:
            secretName: {{ .secretName }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
