{{- range .Values.apps }}
{{- if .autoscaling.enabled }}
---
apiVersion: autoscaling/v2beta2 
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .appName }} 
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: {{ .appName }}
  {{- with .autoscaling }}
  minReplicas: {{ .minReplicas }} 
  maxReplicas: {{ .maxReplicas }}
  metrics: 
  {{- if .memory.enabled }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization 
        averageUtilization: {{ .memory.averageUtilization }} 
  {{- end }}
  {{- if .cpu.enabled }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization 
        averageUtilization: {{ .cpu.averageUtilization }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
