{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-ingress-cm
  namespace: {{ .Release.Namespace }}
data:
  SCRIPT_FILENAME: "/usr/src/app/index.php"
{{- end }}