{{- if .Values.ingress.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{- if ne $key "snippets" }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: {{ template "fullname" . }}-ingress-cm
  name: {{ template "fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  tls:
    - hosts:
       - {{ .Values.ingress.host }}
      {{- if .Values.ingress.secretName  }}
      secretName: {{ .Values.ingress.secretName }}
      {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "fullname" . }}-svc
            port:
              number: {{ .Values.port }}
  {{- end }}