{{- range .Values.apps }}
{{- if .ingress.enabled }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    {{- range $key, $value := .ingress.annotations }}
    {{- if ne $key "snippets" }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: {{ .appName }}-ingress
  name: {{ .appName }}
  namespace: {{ $.Release.Namespace }}
spec:
  tls:
    - hosts:
       - {{ .ingress.host }}
      {{- if .ingress.secretName  }}
      secretName: {{ .ingress.secretName }}
      {{- end }}
  rules:
  - host: {{ .ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .appName }}
            port:
              number: {{ .port }}
{{- end }}
{{- end }}
