{{- $global := .Values.global }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port | default $global.service.port }}
      targetPort: {{ .Values.service.port | default $global.service.port }}
      protocol: TCP
      name: {{ .service.name }}
  selector:
    name: {{ .Values.appName }}
