{{- range .Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .appName }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: {{ .service.name }}
  selector:
    name: {{ .appName }}
{{- end }}
