# Default values for nodejs
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  nodejs:
    repository: ""
    tag: 0.1.0
  pullPolicy: IfNotPresent
ports:
  nodejs: 8080
service:
  name: nodejs
route:
  enabled: true
  host: nodejs-example.srv.fenicio.app
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  - name: APP_RUN
    value: 'npm --loglevel warn start'