---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devs-restricted
rules:
- apiGroups: [""]
  resources:
  - "configmaps"
  - "pods"
  - "pods/log"
  - "pods/portforward"
  - "services"
  - "namespaces"
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - "pods/portforward"
  verbs: ["get", "list", "watch", "create", "delete"]  
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]  