---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-from-pod
  namespace: users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-from-pod
  namespace: users
rules:
  - apiGroups: [""]
    resources: ["secrets","configmaps","serviceaccounts"]
    verbs:
      - get
      - list
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-from-pod
  namespace: users
subjects:
  - kind: ServiceAccount
    name: kubectl-from-pod
roleRef:
  kind: Role
  name: kubectl-from-pod
  apiGroup: rbac.authorization.k8s.io