{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ template "fullname" . }}
spec:
  host: {{ .Values.route.host }}
  path: {{ .Values.route.path }}
  to:
    kind: Service
    name: {{ template "fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end -}}
