apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.ports.nodejs }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    name: {{ template "fullname" . }}